### ISSUE TITLE
Html output extensibility 

### ISSUE THREAD

**Issue by laedit** [Knagis/CommonMark.NET#29]
CommonMark.NET is awesome but I just need to override some html output in some cases.
Actually if I understand well I need to duplicate `HtmlPrinter` in my project and override the tiny part I want.

Is it possible to add some extensibility to the `ProcessStage3`?
For example we can provide a `Func<TextWriter, Block, bool>` which be called in `BlocksToHtmlInner` in the `while (block != null)` part and if it's returns `true` it continue to the next sibling.

Or make `HtmlPrinter` public with `BlocksToHtmlInner` virtual?

I know it's not that simple in either case, but if you are ok I can try something and propose a PR.

**Comment by Knagis** [comment]
The intention is to leave `HtmlPrinter` sealed and non-extendable to save the few milliseconds that could be lost otherwise.

The plan I had was to add another option to the `OutputFormat` enum `CustomDelegate` and add a property to the configuration `Action<Block, CommonMarkSettings, TextWriter> OutputDelegate` (could be different names). This would allow the default output to be overwritten globally. Or maybe instead of a delegate, an instance property like `IPrinter CustomOutputPrinter;`

The intention is that any serious use would require taking the existing `HtmlPrinter` and replacing the particular parts.

Though this would not help those that are looking for quick solution and are not worried if the formatting would take slightly longer. For them there should be an extensible base class that implements everything the same way `HtmlPrinter` does but provides overridable methods. This would also allow the custom printer to keep working as expected if the library adds support for new elements.

**Comment by laedit** [comment]
Thanks for the infos, I will try to propose a PR for the week end.

**Comment by Knagis** [comment]
Released 0.9 with the `HtmlFormatter` class included.

**Comment by laedit** [comment]
Excellent, thanks! :smiley:
