### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by pauldbentley** [Knagis/CommonMark.NET#34]
I would like to be able to support tables as specified in [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#tables) in a C# project I am working on.

Does this component provide support for this?

Many thanks.

**Comment by Knagis** [comment]
CommonMark specification does not include tables (http://talk.commonmark.org/t/tables-in-pure-markdown/81). At this point I don't plan to add support for one of the existing table syntaxes in CommonMark.NET since there is no indication on the details the specification will decide on later and the effort to implement them is non-trivial. 

As per http://talk.commonmark.org/t/roadmap-for-commonmark/1081/8 there could be progress regarding tables during this summer.

**Comment by pauldbentley** [comment]
Hi @Knagis - thanks for your quick reply!  Apologies for not reading the available information first.  It does make very interesting reading.  I am happy to use the component and implement tables using HTML.

**Comment by conanl5566** [comment]
Do you support forms now
