### ISSUE TITLE
Update HTML tag parser to match specification 0.21

### ISSUE THREAD

**Issue by Knagis** [Knagis/CommonMark.NET#39]
Currently 21 tests are failing because of this.

http://spec.commonmark.org/0.21/changes.html

**Comment by elexisvenator** [comment]
Just in addition to this, it appears that html5 tags aren't consistently rendered to the 0.20 spec either.

For example:

```markdown
<markdown-rendered></markdown-rendered>
```

The current version correctly (for 0.20) escapes this and renders:

```html
<p>&lt;markdown-rendered&gt;&lt;/markdown-rendered&gt;</p>
```

But the following gets passed literally:

```markDown
Markdown with some stuff
========================

<p> hello </p>
<markdown-rendered>
</markdown-rendered> <unreleated>
< markdown-rendered >
<  /  markdown-rendered >
<markdown-rendered f-oo bar  baz>
</ markdown-rendered>
<markdown-rendered f-oo="" < foo > "" bar='<bar' >
< markdown-rendered foo = ""'fo'o>""
   bar = '<""ba""r' >
end of tests
```

```html
<h1>Markdown with some stuff</h1>
<p> hello </p>
<markdown-rendered>
</markdown-rendered> <unreleated>
< markdown-rendered >
<  /  markdown-rendered >
<markdown-rendered f-oo bar  baz>
</ markdown-rendered>
<markdown-rendered f-oo=" < foo > " bar='<bar' >
< markdown-rendered foo = "'fo'o>"
   bar = '<"ba"r' >
end of tests
```

Looking into the nodes it appears that all the `<markdown-rendered>` tags get scooped up in the same Html-Block that is created for the P tag.

Thought I would bring this up so that when the html parsing is modified for 0.21 this would be considered.

**Comment by joelmartinez** [comment]
Not sure if there's a better way to vote for an issue to increase in priority ... but :heavy_plus_sign: 

:) but in all seriousness, is there an ETA on this particular issue? we're trying to move from a custom forked version of MarkdownSharp to CommonMark.NET, and this issue is blocking. Any help that a concerned 3rd party could offer?

**Comment by Knagis** [comment]
Finally found the time to update the library. It now passes all tests from specification v.0.22

https://github.com/Knagis/CommonMark.NET/releases/tag/v0.10.0

**Comment by joelmartinez** [comment]
Excellent news! Thanks so much for the update. 

If we want this patch sooner rather than later, we can of course just fetch and build ... But otherwise, when can we expect a new version to be available via nuget (just so we can plan accordingly)?

**Comment by Knagis** [comment]
It has already been released - v.0.10.0
