### ISSUE TITLE
Rendering of HTML content in documents

### ISSUE THREAD

**Issue by NathanCastle** [Knagis/CommonMark.NET#51]
Hello,

I'm working on porting an application to use CommonMark.NET and I've run into an issue with a rendering difference. In our existing library, HTML content is allowed to have spaces and it will still be rendered as html. In this library, if a block of HTML has a line break, the rest of the HTML will be interpreted as a markdown code block. 

See gist for example: https://gist.github.com/NathanCastle/b3ca963a0cef55b664a4

I'm wondering if there is any way that this alternative handling of HTML blocks could be incorporated into the core library, either as the default behavior or as an option. After all, it is pretty common for HTML to have line breaks.

**Comment by Knagis** [comment]
This behavior is according to CommonMark specification, see also the [official CommonMark tryout](http://spec.commonmark.org/dingus/?text=%23%20title%0A%0AEverything%20below%20this%20should%20be%20pure%20HTML%2C%20not%20code%3A%0A%0A%3Ctable%3E%0A%09%3Cthead%3E%0A%09%09%3Ctr%3E%0A%09%09%09%3Ctd%3EHead%201%3C%2Ftd%3E%0A%09%09%09%3Ctd%3EHead%202%3C%2Ftd%3E%0A%09%09%3C%2Ftr%3E%0A%09%3Cthead%3E%0A%09%3Ctbody%3E%0A%0A%09%09%3C!--%20We%20don't%20want%20this%20interpreted%20as%20code%2C%20but%20it%20is.%20--%3E%0A%09%09%3Ctr%3E%0A%09%09%09%3Ctd%3Ecell1%3C%2Ftd%3E%0A%09%09%09%3Ctd%3Ecell1%3C%2Ftd%3E%0A%09%09%3C%2Ftr%3E%0A%09%3C%2Ftbody%3E%0A%3C%2Ftable%3E).

The problem with the your expected behavior is that the CommonMark parser has to be expanded to a full HTML parser as well - since it has to parse the HTML blocks looking if the opening tag has been closed - there could be nested `<table>` elements etc.

Another big issue with this is that it could require heavy backtracking (in case when the `</table>` element was not found) that would significantly hurt the performance.

You can raise the issue on <http://talk.commonmark.org>.
